#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v2
# autospec commit: 250a666
#
Name     : perl-DateTime-Locale
Version  : 1.40
Release  : 61
URL      : https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Locale-1.40.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Locale-1.40.tar.gz
Summary  : 'Localization support for DateTime.pm'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0 ICU
Requires: perl-DateTime-Locale-license = %{version}-%{release}
Requires: perl-DateTime-Locale-perl = %{version}-%{release}
Requires: perl(B::Hooks::EndOfScope)
Requires: perl(File::ShareDir)
Requires: perl(Module::Implementation)
BuildRequires : buildreq-cpan
BuildRequires : perl(B::Hooks::EndOfScope)
BuildRequires : perl(CPAN::Meta::Check)
BuildRequires : perl(Class::Data::Inheritable)
BuildRequires : perl(Class::Inspector)
BuildRequires : perl(Class::Tiny)
BuildRequires : perl(Devel::StackTrace)
BuildRequires : perl(Eval::Closure)
BuildRequires : perl(Exception::Class)
BuildRequires : perl(File::Copy::Recursive)
BuildRequires : perl(File::ShareDir)
BuildRequires : perl(File::ShareDir::Install)
BuildRequires : perl(MRO::Compat)
BuildRequires : perl(Module::Implementation)
BuildRequires : perl(Module::Runtime)
BuildRequires : perl(Package::Stash)
BuildRequires : perl(Params::ValidationCompiler)
BuildRequires : perl(Path::Tiny)
BuildRequires : perl(Role::Tiny)
BuildRequires : perl(Specio::Declare)
BuildRequires : perl(Specio::Library::String)
BuildRequires : perl(Sub::Exporter::Progressive)
BuildRequires : perl(Sub::Identify)
BuildRequires : perl(Test2::Plugin::NoWarnings)
BuildRequires : perl(Test2::Require::Module)
BuildRequires : perl(Test2::V0)
BuildRequires : perl(Test::File::ShareDir::Dist)
BuildRequires : perl(Try::Tiny)
BuildRequires : perl(Variable::Magic)
BuildRequires : perl(namespace::autoclean)
BuildRequires : perl(namespace::clean)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# NAME
DateTime::Locale - Localization support for DateTime.pm
# VERSION
version 1.40

%package dev
Summary: dev components for the perl-DateTime-Locale package.
Group: Development
Provides: perl-DateTime-Locale-devel = %{version}-%{release}
Requires: perl-DateTime-Locale = %{version}-%{release}

%description dev
dev components for the perl-DateTime-Locale package.


%package license
Summary: license components for the perl-DateTime-Locale package.
Group: Default

%description license
license components for the perl-DateTime-Locale package.


%package perl
Summary: perl components for the perl-DateTime-Locale package.
Group: Default
Requires: perl-DateTime-Locale = %{version}-%{release}

%description perl
perl components for the perl-DateTime-Locale package.


%prep
%setup -q -n DateTime-Locale-1.40
cd %{_builddir}/DateTime-Locale-1.40
pushd ..
cp -a DateTime-Locale-1.40 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test || :

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-DateTime-Locale
cp %{_builddir}/DateTime-Locale-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-DateTime-Locale/7a3ae67849cbe4c41d51b6587fba9867878d99ed || :
cp %{_builddir}/DateTime-Locale-%{version}/LICENSE.cldr %{buildroot}/usr/share/package-licenses/perl-DateTime-Locale/96f969d89e371129342f90e4c815e4abdb7461c4 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/DateTime::Locale.3
/usr/share/man/man3/DateTime::Locale::Base.3
/usr/share/man/man3/DateTime::Locale::Catalog.3
/usr/share/man/man3/DateTime::Locale::Conflicts.3
/usr/share/man/man3/DateTime::Locale::Data.3
/usr/share/man/man3/DateTime::Locale::FromData.3
/usr/share/man/man3/DateTime::Locale::Util.3
/usr/share/man/man3/DateTime::Locale::aa.3
/usr/share/man/man3/DateTime::Locale::aa_DJ.3
/usr/share/man/man3/DateTime::Locale::aa_ER.3
/usr/share/man/man3/DateTime::Locale::aa_ET.3
/usr/share/man/man3/DateTime::Locale::ab.3
/usr/share/man/man3/DateTime::Locale::ab_GE.3
/usr/share/man/man3/DateTime::Locale::af.3
/usr/share/man/man3/DateTime::Locale::af_NA.3
/usr/share/man/man3/DateTime::Locale::af_ZA.3
/usr/share/man/man3/DateTime::Locale::agq.3
/usr/share/man/man3/DateTime::Locale::agq_CM.3
/usr/share/man/man3/DateTime::Locale::ak.3
/usr/share/man/man3/DateTime::Locale::ak_GH.3
/usr/share/man/man3/DateTime::Locale::am.3
/usr/share/man/man3/DateTime::Locale::am_ET.3
/usr/share/man/man3/DateTime::Locale::an.3
/usr/share/man/man3/DateTime::Locale::an_ES.3
/usr/share/man/man3/DateTime::Locale::ann.3
/usr/share/man/man3/DateTime::Locale::ann_NG.3
/usr/share/man/man3/DateTime::Locale::apc_SY.3
/usr/share/man/man3/DateTime::Locale::ar.3
/usr/share/man/man3/DateTime::Locale::ar_001.3
/usr/share/man/man3/DateTime::Locale::ar_AE.3
/usr/share/man/man3/DateTime::Locale::ar_BH.3
/usr/share/man/man3/DateTime::Locale::ar_DJ.3
/usr/share/man/man3/DateTime::Locale::ar_DZ.3
/usr/share/man/man3/DateTime::Locale::ar_EG.3
/usr/share/man/man3/DateTime::Locale::ar_EH.3
/usr/share/man/man3/DateTime::Locale::ar_ER.3
/usr/share/man/man3/DateTime::Locale::ar_IL.3
/usr/share/man/man3/DateTime::Locale::ar_IQ.3
/usr/share/man/man3/DateTime::Locale::ar_JO.3
/usr/share/man/man3/DateTime::Locale::ar_KM.3
/usr/share/man/man3/DateTime::Locale::ar_KW.3
/usr/share/man/man3/DateTime::Locale::ar_LB.3
/usr/share/man/man3/DateTime::Locale::ar_LY.3
/usr/share/man/man3/DateTime::Locale::ar_MA.3
/usr/share/man/man3/DateTime::Locale::ar_MR.3
/usr/share/man/man3/DateTime::Locale::ar_OM.3
/usr/share/man/man3/DateTime::Locale::ar_PS.3
/usr/share/man/man3/DateTime::Locale::ar_QA.3
/usr/share/man/man3/DateTime::Locale::ar_SA.3
/usr/share/man/man3/DateTime::Locale::ar_SD.3
/usr/share/man/man3/DateTime::Locale::ar_SO.3
/usr/share/man/man3/DateTime::Locale::ar_SS.3
/usr/share/man/man3/DateTime::Locale::ar_SY.3
/usr/share/man/man3/DateTime::Locale::ar_TD.3
/usr/share/man/man3/DateTime::Locale::ar_TN.3
/usr/share/man/man3/DateTime::Locale::ar_YE.3
/usr/share/man/man3/DateTime::Locale::arn.3
/usr/share/man/man3/DateTime::Locale::arn_CL.3
/usr/share/man/man3/DateTime::Locale::as.3
/usr/share/man/man3/DateTime::Locale::as_IN.3
/usr/share/man/man3/DateTime::Locale::asa.3
/usr/share/man/man3/DateTime::Locale::asa_TZ.3
/usr/share/man/man3/DateTime::Locale::ast.3
/usr/share/man/man3/DateTime::Locale::ast_ES.3
/usr/share/man/man3/DateTime::Locale::az.3
/usr/share/man/man3/DateTime::Locale::az_Arab.3
/usr/share/man/man3/DateTime::Locale::az_Arab_IQ.3
/usr/share/man/man3/DateTime::Locale::az_Arab_IR.3
/usr/share/man/man3/DateTime::Locale::az_Arab_TR.3
/usr/share/man/man3/DateTime::Locale::az_Cyrl.3
/usr/share/man/man3/DateTime::Locale::az_Cyrl_AZ.3
/usr/share/man/man3/DateTime::Locale::az_Latn.3
/usr/share/man/man3/DateTime::Locale::az_Latn_AZ.3
/usr/share/man/man3/DateTime::Locale::ba.3
/usr/share/man/man3/DateTime::Locale::ba_RU.3
/usr/share/man/man3/DateTime::Locale::bal.3
/usr/share/man/man3/DateTime::Locale::bal_Arab.3
/usr/share/man/man3/DateTime::Locale::bal_Arab_PK.3
/usr/share/man/man3/DateTime::Locale::bal_Latn.3
/usr/share/man/man3/DateTime::Locale::bal_Latn_PK.3
/usr/share/man/man3/DateTime::Locale::bas.3
/usr/share/man/man3/DateTime::Locale::bas_CM.3
/usr/share/man/man3/DateTime::Locale::be.3
/usr/share/man/man3/DateTime::Locale::be_BY.3
/usr/share/man/man3/DateTime::Locale::be_tarask.3
/usr/share/man/man3/DateTime::Locale::bem.3
/usr/share/man/man3/DateTime::Locale::bem_ZM.3
/usr/share/man/man3/DateTime::Locale::bez.3
/usr/share/man/man3/DateTime::Locale::bez_TZ.3
/usr/share/man/man3/DateTime::Locale::bg.3
/usr/share/man/man3/DateTime::Locale::bg_BG.3
/usr/share/man/man3/DateTime::Locale::bgc.3
/usr/share/man/man3/DateTime::Locale::bgc_IN.3
/usr/share/man/man3/DateTime::Locale::bgn.3
/usr/share/man/man3/DateTime::Locale::bgn_AE.3
/usr/share/man/man3/DateTime::Locale::bgn_AF.3
/usr/share/man/man3/DateTime::Locale::bgn_IR.3
/usr/share/man/man3/DateTime::Locale::bgn_OM.3
/usr/share/man/man3/DateTime::Locale::bgn_PK.3
/usr/share/man/man3/DateTime::Locale::bho.3
/usr/share/man/man3/DateTime::Locale::bho_IN.3
/usr/share/man/man3/DateTime::Locale::blt.3
/usr/share/man/man3/DateTime::Locale::blt_VN.3
/usr/share/man/man3/DateTime::Locale::bm.3
/usr/share/man/man3/DateTime::Locale::bm_ML.3
/usr/share/man/man3/DateTime::Locale::bm_Nkoo.3
/usr/share/man/man3/DateTime::Locale::bm_Nkoo_ML.3
/usr/share/man/man3/DateTime::Locale::bn.3
/usr/share/man/man3/DateTime::Locale::bn_BD.3
/usr/share/man/man3/DateTime::Locale::bn_IN.3
/usr/share/man/man3/DateTime::Locale::bo.3
/usr/share/man/man3/DateTime::Locale::bo_CN.3
/usr/share/man/man3/DateTime::Locale::bo_IN.3
/usr/share/man/man3/DateTime::Locale::br.3
/usr/share/man/man3/DateTime::Locale::br_FR.3
/usr/share/man/man3/DateTime::Locale::brx.3
/usr/share/man/man3/DateTime::Locale::brx_IN.3
/usr/share/man/man3/DateTime::Locale::bs.3
/usr/share/man/man3/DateTime::Locale::bs_Cyrl.3
/usr/share/man/man3/DateTime::Locale::bs_Cyrl_BA.3
/usr/share/man/man3/DateTime::Locale::bs_Latn.3
/usr/share/man/man3/DateTime::Locale::bs_Latn_BA.3
/usr/share/man/man3/DateTime::Locale::bss.3
/usr/share/man/man3/DateTime::Locale::bss_CM.3
/usr/share/man/man3/DateTime::Locale::byn.3
/usr/share/man/man3/DateTime::Locale::byn_ER.3
/usr/share/man/man3/DateTime::Locale::ca.3
/usr/share/man/man3/DateTime::Locale::ca_AD.3
/usr/share/man/man3/DateTime::Locale::ca_ES.3
/usr/share/man/man3/DateTime::Locale::ca_ES_valencia.3
/usr/share/man/man3/DateTime::Locale::ca_FR.3
/usr/share/man/man3/DateTime::Locale::ca_IT.3
/usr/share/man/man3/DateTime::Locale::cad.3
/usr/share/man/man3/DateTime::Locale::cad_US.3
/usr/share/man/man3/DateTime::Locale::cch.3
/usr/share/man/man3/DateTime::Locale::cch_NG.3
/usr/share/man/man3/DateTime::Locale::ccp.3
/usr/share/man/man3/DateTime::Locale::ccp_BD.3
/usr/share/man/man3/DateTime::Locale::ccp_IN.3
/usr/share/man/man3/DateTime::Locale::ce.3
/usr/share/man/man3/DateTime::Locale::ce_RU.3
/usr/share/man/man3/DateTime::Locale::ceb.3
/usr/share/man/man3/DateTime::Locale::ceb_PH.3
/usr/share/man/man3/DateTime::Locale::cgg.3
/usr/share/man/man3/DateTime::Locale::cgg_UG.3
/usr/share/man/man3/DateTime::Locale::cho.3
/usr/share/man/man3/DateTime::Locale::cho_US.3
/usr/share/man/man3/DateTime::Locale::chr.3
/usr/share/man/man3/DateTime::Locale::chr_US.3
/usr/share/man/man3/DateTime::Locale::cic.3
/usr/share/man/man3/DateTime::Locale::cic_US.3
/usr/share/man/man3/DateTime::Locale::ckb.3
/usr/share/man/man3/DateTime::Locale::ckb_IQ.3
/usr/share/man/man3/DateTime::Locale::ckb_IR.3
/usr/share/man/man3/DateTime::Locale::co.3
/usr/share/man/man3/DateTime::Locale::co_FR.3
/usr/share/man/man3/DateTime::Locale::cs.3
/usr/share/man/man3/DateTime::Locale::cs_CZ.3
/usr/share/man/man3/DateTime::Locale::cu.3
/usr/share/man/man3/DateTime::Locale::cu_RU.3
/usr/share/man/man3/DateTime::Locale::cv.3
/usr/share/man/man3/DateTime::Locale::cv_RU.3
/usr/share/man/man3/DateTime::Locale::cy.3
/usr/share/man/man3/DateTime::Locale::cy_GB.3
/usr/share/man/man3/DateTime::Locale::da.3
/usr/share/man/man3/DateTime::Locale::da_DK.3
/usr/share/man/man3/DateTime::Locale::da_GL.3
/usr/share/man/man3/DateTime::Locale::dav.3
/usr/share/man/man3/DateTime::Locale::dav_KE.3
/usr/share/man/man3/DateTime::Locale::de.3
/usr/share/man/man3/DateTime::Locale::de_AT.3
/usr/share/man/man3/DateTime::Locale::de_BE.3
/usr/share/man/man3/DateTime::Locale::de_CH.3
/usr/share/man/man3/DateTime::Locale::de_DE.3
/usr/share/man/man3/DateTime::Locale::de_IT.3
/usr/share/man/man3/DateTime::Locale::de_LI.3
/usr/share/man/man3/DateTime::Locale::de_LU.3
/usr/share/man/man3/DateTime::Locale::dje.3
/usr/share/man/man3/DateTime::Locale::dje_NE.3
/usr/share/man/man3/DateTime::Locale::doi.3
/usr/share/man/man3/DateTime::Locale::doi_IN.3
/usr/share/man/man3/DateTime::Locale::dsb.3
/usr/share/man/man3/DateTime::Locale::dsb_DE.3
/usr/share/man/man3/DateTime::Locale::dua.3
/usr/share/man/man3/DateTime::Locale::dua_CM.3
/usr/share/man/man3/DateTime::Locale::dv.3
/usr/share/man/man3/DateTime::Locale::dv_MV.3
/usr/share/man/man3/DateTime::Locale::dyo.3
/usr/share/man/man3/DateTime::Locale::dyo_SN.3
/usr/share/man/man3/DateTime::Locale::dz.3
/usr/share/man/man3/DateTime::Locale::dz_BT.3
/usr/share/man/man3/DateTime::Locale::ebu.3
/usr/share/man/man3/DateTime::Locale::ebu_KE.3
/usr/share/man/man3/DateTime::Locale::ee.3
/usr/share/man/man3/DateTime::Locale::ee_GH.3
/usr/share/man/man3/DateTime::Locale::ee_TG.3
/usr/share/man/man3/DateTime::Locale::el.3
/usr/share/man/man3/DateTime::Locale::el_CY.3
/usr/share/man/man3/DateTime::Locale::el_GR.3
/usr/share/man/man3/DateTime::Locale::el_polyton.3
/usr/share/man/man3/DateTime::Locale::en.3
/usr/share/man/man3/DateTime::Locale::en_001.3
/usr/share/man/man3/DateTime::Locale::en_150.3
/usr/share/man/man3/DateTime::Locale::en_AE.3
/usr/share/man/man3/DateTime::Locale::en_AG.3
/usr/share/man/man3/DateTime::Locale::en_AI.3
/usr/share/man/man3/DateTime::Locale::en_AS.3
/usr/share/man/man3/DateTime::Locale::en_AT.3
/usr/share/man/man3/DateTime::Locale::en_AU.3
/usr/share/man/man3/DateTime::Locale::en_BB.3
/usr/share/man/man3/DateTime::Locale::en_BE.3
/usr/share/man/man3/DateTime::Locale::en_BI.3
/usr/share/man/man3/DateTime::Locale::en_BM.3
/usr/share/man/man3/DateTime::Locale::en_BS.3
/usr/share/man/man3/DateTime::Locale::en_BW.3
/usr/share/man/man3/DateTime::Locale::en_BZ.3
/usr/share/man/man3/DateTime::Locale::en_CA.3
/usr/share/man/man3/DateTime::Locale::en_CC.3
/usr/share/man/man3/DateTime::Locale::en_CH.3
/usr/share/man/man3/DateTime::Locale::en_CK.3
/usr/share/man/man3/DateTime::Locale::en_CM.3
/usr/share/man/man3/DateTime::Locale::en_CX.3
/usr/share/man/man3/DateTime::Locale::en_CY.3
/usr/share/man/man3/DateTime::Locale::en_DE.3
/usr/share/man/man3/DateTime::Locale::en_DG.3
/usr/share/man/man3/DateTime::Locale::en_DK.3
/usr/share/man/man3/DateTime::Locale::en_DM.3
/usr/share/man/man3/DateTime::Locale::en_Dsrt.3
/usr/share/man/man3/DateTime::Locale::en_Dsrt_US.3
/usr/share/man/man3/DateTime::Locale::en_ER.3
/usr/share/man/man3/DateTime::Locale::en_FI.3
/usr/share/man/man3/DateTime::Locale::en_FJ.3
/usr/share/man/man3/DateTime::Locale::en_FK.3
/usr/share/man/man3/DateTime::Locale::en_FM.3
/usr/share/man/man3/DateTime::Locale::en_GB.3
/usr/share/man/man3/DateTime::Locale::en_GD.3
/usr/share/man/man3/DateTime::Locale::en_GG.3
/usr/share/man/man3/DateTime::Locale::en_GH.3
/usr/share/man/man3/DateTime::Locale::en_GI.3
/usr/share/man/man3/DateTime::Locale::en_GM.3
/usr/share/man/man3/DateTime::Locale::en_GU.3
/usr/share/man/man3/DateTime::Locale::en_GY.3
/usr/share/man/man3/DateTime::Locale::en_HK.3
/usr/share/man/man3/DateTime::Locale::en_IE.3
/usr/share/man/man3/DateTime::Locale::en_IL.3
/usr/share/man/man3/DateTime::Locale::en_IM.3
/usr/share/man/man3/DateTime::Locale::en_IN.3
/usr/share/man/man3/DateTime::Locale::en_IO.3
/usr/share/man/man3/DateTime::Locale::en_JE.3
/usr/share/man/man3/DateTime::Locale::en_JM.3
/usr/share/man/man3/DateTime::Locale::en_KE.3
/usr/share/man/man3/DateTime::Locale::en_KI.3
/usr/share/man/man3/DateTime::Locale::en_KN.3
/usr/share/man/man3/DateTime::Locale::en_KY.3
/usr/share/man/man3/DateTime::Locale::en_LC.3
/usr/share/man/man3/DateTime::Locale::en_LR.3
/usr/share/man/man3/DateTime::Locale::en_LS.3
/usr/share/man/man3/DateTime::Locale::en_MG.3
/usr/share/man/man3/DateTime::Locale::en_MH.3
/usr/share/man/man3/DateTime::Locale::en_MO.3
/usr/share/man/man3/DateTime::Locale::en_MP.3
/usr/share/man/man3/DateTime::Locale::en_MS.3
/usr/share/man/man3/DateTime::Locale::en_MT.3
/usr/share/man/man3/DateTime::Locale::en_MU.3
/usr/share/man/man3/DateTime::Locale::en_MV.3
/usr/share/man/man3/DateTime::Locale::en_MW.3
/usr/share/man/man3/DateTime::Locale::en_MY.3
/usr/share/man/man3/DateTime::Locale::en_NA.3
/usr/share/man/man3/DateTime::Locale::en_NF.3
/usr/share/man/man3/DateTime::Locale::en_NG.3
/usr/share/man/man3/DateTime::Locale::en_NL.3
/usr/share/man/man3/DateTime::Locale::en_NR.3
/usr/share/man/man3/DateTime::Locale::en_NU.3
/usr/share/man/man3/DateTime::Locale::en_NZ.3
/usr/share/man/man3/DateTime::Locale::en_PG.3
/usr/share/man/man3/DateTime::Locale::en_PH.3
/usr/share/man/man3/DateTime::Locale::en_PK.3
/usr/share/man/man3/DateTime::Locale::en_PN.3
/usr/share/man/man3/DateTime::Locale::en_PR.3
/usr/share/man/man3/DateTime::Locale::en_PW.3
/usr/share/man/man3/DateTime::Locale::en_RW.3
/usr/share/man/man3/DateTime::Locale::en_SB.3
/usr/share/man/man3/DateTime::Locale::en_SC.3
/usr/share/man/man3/DateTime::Locale::en_SD.3
/usr/share/man/man3/DateTime::Locale::en_SE.3
/usr/share/man/man3/DateTime::Locale::en_SG.3
/usr/share/man/man3/DateTime::Locale::en_SH.3
/usr/share/man/man3/DateTime::Locale::en_SI.3
/usr/share/man/man3/DateTime::Locale::en_SL.3
/usr/share/man/man3/DateTime::Locale::en_SS.3
/usr/share/man/man3/DateTime::Locale::en_SX.3
/usr/share/man/man3/DateTime::Locale::en_SZ.3
/usr/share/man/man3/DateTime::Locale::en_Shaw.3
/usr/share/man/man3/DateTime::Locale::en_Shaw_GB.3
/usr/share/man/man3/DateTime::Locale::en_TC.3
/usr/share/man/man3/DateTime::Locale::en_TK.3
/usr/share/man/man3/DateTime::Locale::en_TO.3
/usr/share/man/man3/DateTime::Locale::en_TT.3
/usr/share/man/man3/DateTime::Locale::en_TV.3
/usr/share/man/man3/DateTime::Locale::en_TZ.3
/usr/share/man/man3/DateTime::Locale::en_UG.3
/usr/share/man/man3/DateTime::Locale::en_UM.3
/usr/share/man/man3/DateTime::Locale::en_US.3
/usr/share/man/man3/DateTime::Locale::en_VC.3
/usr/share/man/man3/DateTime::Locale::en_VG.3
/usr/share/man/man3/DateTime::Locale::en_VI.3
/usr/share/man/man3/DateTime::Locale::en_VU.3
/usr/share/man/man3/DateTime::Locale::en_WS.3
/usr/share/man/man3/DateTime::Locale::en_ZA.3
/usr/share/man/man3/DateTime::Locale::en_ZM.3
/usr/share/man/man3/DateTime::Locale::en_ZW.3
/usr/share/man/man3/DateTime::Locale::eo.3
/usr/share/man/man3/DateTime::Locale::eo_001.3
/usr/share/man/man3/DateTime::Locale::es.3
/usr/share/man/man3/DateTime::Locale::es_419.3
/usr/share/man/man3/DateTime::Locale::es_AR.3
/usr/share/man/man3/DateTime::Locale::es_BO.3
/usr/share/man/man3/DateTime::Locale::es_BR.3
/usr/share/man/man3/DateTime::Locale::es_BZ.3
/usr/share/man/man3/DateTime::Locale::es_CL.3
/usr/share/man/man3/DateTime::Locale::es_CO.3
/usr/share/man/man3/DateTime::Locale::es_CR.3
/usr/share/man/man3/DateTime::Locale::es_CU.3
/usr/share/man/man3/DateTime::Locale::es_DO.3
/usr/share/man/man3/DateTime::Locale::es_EA.3
/usr/share/man/man3/DateTime::Locale::es_EC.3
/usr/share/man/man3/DateTime::Locale::es_ES.3
/usr/share/man/man3/DateTime::Locale::es_GQ.3
/usr/share/man/man3/DateTime::Locale::es_GT.3
/usr/share/man/man3/DateTime::Locale::es_HN.3
/usr/share/man/man3/DateTime::Locale::es_IC.3
/usr/share/man/man3/DateTime::Locale::es_MX.3
/usr/share/man/man3/DateTime::Locale::es_NI.3
/usr/share/man/man3/DateTime::Locale::es_PA.3
/usr/share/man/man3/DateTime::Locale::es_PE.3
/usr/share/man/man3/DateTime::Locale::es_PH.3
/usr/share/man/man3/DateTime::Locale::es_PR.3
/usr/share/man/man3/DateTime::Locale::es_PY.3
/usr/share/man/man3/DateTime::Locale::es_SV.3
/usr/share/man/man3/DateTime::Locale::es_US.3
/usr/share/man/man3/DateTime::Locale::es_UY.3
/usr/share/man/man3/DateTime::Locale::es_VE.3
/usr/share/man/man3/DateTime::Locale::et.3
/usr/share/man/man3/DateTime::Locale::et_EE.3
/usr/share/man/man3/DateTime::Locale::eu.3
/usr/share/man/man3/DateTime::Locale::eu_ES.3
/usr/share/man/man3/DateTime::Locale::ewo.3
/usr/share/man/man3/DateTime::Locale::ewo_CM.3
/usr/share/man/man3/DateTime::Locale::fa.3
/usr/share/man/man3/DateTime::Locale::fa_AF.3
/usr/share/man/man3/DateTime::Locale::fa_IR.3
/usr/share/man/man3/DateTime::Locale::ff.3
/usr/share/man/man3/DateTime::Locale::ff_Adlm.3
/usr/share/man/man3/DateTime::Locale::ff_Adlm_BF.3
/usr/share/man/man3/DateTime::Locale::ff_Adlm_CM.3
/usr/share/man/man3/DateTime::Locale::ff_Adlm_GH.3
/usr/share/man/man3/DateTime::Locale::ff_Adlm_GM.3
/usr/share/man/man3/DateTime::Locale::ff_Adlm_GN.3
/usr/share/man/man3/DateTime::Locale::ff_Adlm_GW.3
/usr/share/man/man3/DateTime::Locale::ff_Adlm_LR.3
/usr/share/man/man3/DateTime::Locale::ff_Adlm_MR.3
/usr/share/man/man3/DateTime::Locale::ff_Adlm_NE.3
/usr/share/man/man3/DateTime::Locale::ff_Adlm_NG.3
/usr/share/man/man3/DateTime::Locale::ff_Adlm_SL.3
/usr/share/man/man3/DateTime::Locale::ff_Adlm_SN.3
/usr/share/man/man3/DateTime::Locale::ff_Latn.3
/usr/share/man/man3/DateTime::Locale::ff_Latn_BF.3
/usr/share/man/man3/DateTime::Locale::ff_Latn_CM.3
/usr/share/man/man3/DateTime::Locale::ff_Latn_GH.3
/usr/share/man/man3/DateTime::Locale::ff_Latn_GM.3
/usr/share/man/man3/DateTime::Locale::ff_Latn_GN.3
/usr/share/man/man3/DateTime::Locale::ff_Latn_GW.3
/usr/share/man/man3/DateTime::Locale::ff_Latn_LR.3
/usr/share/man/man3/DateTime::Locale::ff_Latn_MR.3
/usr/share/man/man3/DateTime::Locale::ff_Latn_NE.3
/usr/share/man/man3/DateTime::Locale::ff_Latn_NG.3
/usr/share/man/man3/DateTime::Locale::ff_Latn_SL.3
/usr/share/man/man3/DateTime::Locale::ff_Latn_SN.3
/usr/share/man/man3/DateTime::Locale::fi.3
/usr/share/man/man3/DateTime::Locale::fi_FI.3
/usr/share/man/man3/DateTime::Locale::fil.3
/usr/share/man/man3/DateTime::Locale::fil_PH.3
/usr/share/man/man3/DateTime::Locale::fo.3
/usr/share/man/man3/DateTime::Locale::fo_DK.3
/usr/share/man/man3/DateTime::Locale::fo_FO.3
/usr/share/man/man3/DateTime::Locale::fr.3
/usr/share/man/man3/DateTime::Locale::fr_BE.3
/usr/share/man/man3/DateTime::Locale::fr_BF.3
/usr/share/man/man3/DateTime::Locale::fr_BI.3
/usr/share/man/man3/DateTime::Locale::fr_BJ.3
/usr/share/man/man3/DateTime::Locale::fr_BL.3
/usr/share/man/man3/DateTime::Locale::fr_CA.3
/usr/share/man/man3/DateTime::Locale::fr_CD.3
/usr/share/man/man3/DateTime::Locale::fr_CF.3
/usr/share/man/man3/DateTime::Locale::fr_CG.3
/usr/share/man/man3/DateTime::Locale::fr_CH.3
/usr/share/man/man3/DateTime::Locale::fr_CI.3
/usr/share/man/man3/DateTime::Locale::fr_CM.3
/usr/share/man/man3/DateTime::Locale::fr_DJ.3
/usr/share/man/man3/DateTime::Locale::fr_DZ.3
/usr/share/man/man3/DateTime::Locale::fr_FR.3
/usr/share/man/man3/DateTime::Locale::fr_GA.3
/usr/share/man/man3/DateTime::Locale::fr_GF.3
/usr/share/man/man3/DateTime::Locale::fr_GN.3
/usr/share/man/man3/DateTime::Locale::fr_GP.3
/usr/share/man/man3/DateTime::Locale::fr_GQ.3
/usr/share/man/man3/DateTime::Locale::fr_HT.3
/usr/share/man/man3/DateTime::Locale::fr_KM.3
/usr/share/man/man3/DateTime::Locale::fr_LU.3
/usr/share/man/man3/DateTime::Locale::fr_MA.3
/usr/share/man/man3/DateTime::Locale::fr_MC.3
/usr/share/man/man3/DateTime::Locale::fr_MF.3
/usr/share/man/man3/DateTime::Locale::fr_MG.3
/usr/share/man/man3/DateTime::Locale::fr_ML.3
/usr/share/man/man3/DateTime::Locale::fr_MQ.3
/usr/share/man/man3/DateTime::Locale::fr_MR.3
/usr/share/man/man3/DateTime::Locale::fr_MU.3
/usr/share/man/man3/DateTime::Locale::fr_NC.3
/usr/share/man/man3/DateTime::Locale::fr_NE.3
/usr/share/man/man3/DateTime::Locale::fr_PF.3
/usr/share/man/man3/DateTime::Locale::fr_PM.3
/usr/share/man/man3/DateTime::Locale::fr_RE.3
/usr/share/man/man3/DateTime::Locale::fr_RW.3
/usr/share/man/man3/DateTime::Locale::fr_SC.3
/usr/share/man/man3/DateTime::Locale::fr_SN.3
/usr/share/man/man3/DateTime::Locale::fr_SY.3
/usr/share/man/man3/DateTime::Locale::fr_TD.3
/usr/share/man/man3/DateTime::Locale::fr_TG.3
/usr/share/man/man3/DateTime::Locale::fr_TN.3
/usr/share/man/man3/DateTime::Locale::fr_VU.3
/usr/share/man/man3/DateTime::Locale::fr_WF.3
/usr/share/man/man3/DateTime::Locale::fr_YT.3
/usr/share/man/man3/DateTime::Locale::frr.3
/usr/share/man/man3/DateTime::Locale::frr_DE.3
/usr/share/man/man3/DateTime::Locale::fur.3
/usr/share/man/man3/DateTime::Locale::fur_IT.3
/usr/share/man/man3/DateTime::Locale::fy.3
/usr/share/man/man3/DateTime::Locale::fy_NL.3
/usr/share/man/man3/DateTime::Locale::ga.3
/usr/share/man/man3/DateTime::Locale::ga_GB.3
/usr/share/man/man3/DateTime::Locale::ga_IE.3
/usr/share/man/man3/DateTime::Locale::gaa.3
/usr/share/man/man3/DateTime::Locale::gaa_GH.3
/usr/share/man/man3/DateTime::Locale::gd.3
/usr/share/man/man3/DateTime::Locale::gd_GB.3
/usr/share/man/man3/DateTime::Locale::gez.3
/usr/share/man/man3/DateTime::Locale::gez_ER.3
/usr/share/man/man3/DateTime::Locale::gez_ET.3
/usr/share/man/man3/DateTime::Locale::gl.3
/usr/share/man/man3/DateTime::Locale::gl_ES.3
/usr/share/man/man3/DateTime::Locale::gn.3
/usr/share/man/man3/DateTime::Locale::gn_PY.3
/usr/share/man/man3/DateTime::Locale::gsw.3
/usr/share/man/man3/DateTime::Locale::gsw_CH.3
/usr/share/man/man3/DateTime::Locale::gsw_FR.3
/usr/share/man/man3/DateTime::Locale::gsw_LI.3
/usr/share/man/man3/DateTime::Locale::gu.3
/usr/share/man/man3/DateTime::Locale::gu_IN.3
/usr/share/man/man3/DateTime::Locale::guz.3
/usr/share/man/man3/DateTime::Locale::guz_KE.3
/usr/share/man/man3/DateTime::Locale::gv.3
/usr/share/man/man3/DateTime::Locale::gv_IM.3
/usr/share/man/man3/DateTime::Locale::ha.3
/usr/share/man/man3/DateTime::Locale::ha_Arab.3
/usr/share/man/man3/DateTime::Locale::ha_Arab_NG.3
/usr/share/man/man3/DateTime::Locale::ha_Arab_SD.3
/usr/share/man/man3/DateTime::Locale::ha_GH.3
/usr/share/man/man3/DateTime::Locale::ha_NE.3
/usr/share/man/man3/DateTime::Locale::ha_NG.3
/usr/share/man/man3/DateTime::Locale::haw.3
/usr/share/man/man3/DateTime::Locale::haw_US.3
/usr/share/man/man3/DateTime::Locale::he.3
/usr/share/man/man3/DateTime::Locale::he_IL.3
/usr/share/man/man3/DateTime::Locale::hi.3
/usr/share/man/man3/DateTime::Locale::hi_IN.3
/usr/share/man/man3/DateTime::Locale::hi_Latn.3
/usr/share/man/man3/DateTime::Locale::hi_Latn_IN.3
/usr/share/man/man3/DateTime::Locale::hnj.3
/usr/share/man/man3/DateTime::Locale::hnj_Hmnp.3
/usr/share/man/man3/DateTime::Locale::hnj_Hmnp_US.3
/usr/share/man/man3/DateTime::Locale::hr.3
/usr/share/man/man3/DateTime::Locale::hr_BA.3
/usr/share/man/man3/DateTime::Locale::hr_HR.3
/usr/share/man/man3/DateTime::Locale::hsb.3
/usr/share/man/man3/DateTime::Locale::hsb_DE.3
/usr/share/man/man3/DateTime::Locale::hu.3
/usr/share/man/man3/DateTime::Locale::hu_HU.3
/usr/share/man/man3/DateTime::Locale::hy.3
/usr/share/man/man3/DateTime::Locale::hy_AM.3
/usr/share/man/man3/DateTime::Locale::ia.3
/usr/share/man/man3/DateTime::Locale::ia_001.3
/usr/share/man/man3/DateTime::Locale::id.3
/usr/share/man/man3/DateTime::Locale::id_ID.3
/usr/share/man/man3/DateTime::Locale::ig.3
/usr/share/man/man3/DateTime::Locale::ig_NG.3
/usr/share/man/man3/DateTime::Locale::ii.3
/usr/share/man/man3/DateTime::Locale::ii_CN.3
/usr/share/man/man3/DateTime::Locale::io.3
/usr/share/man/man3/DateTime::Locale::io_001.3
/usr/share/man/man3/DateTime::Locale::is.3
/usr/share/man/man3/DateTime::Locale::is_IS.3
/usr/share/man/man3/DateTime::Locale::it.3
/usr/share/man/man3/DateTime::Locale::it_CH.3
/usr/share/man/man3/DateTime::Locale::it_IT.3
/usr/share/man/man3/DateTime::Locale::it_SM.3
/usr/share/man/man3/DateTime::Locale::it_VA.3
/usr/share/man/man3/DateTime::Locale::iu.3
/usr/share/man/man3/DateTime::Locale::iu_CA.3
/usr/share/man/man3/DateTime::Locale::iu_Latn.3
/usr/share/man/man3/DateTime::Locale::iu_Latn_CA.3
/usr/share/man/man3/DateTime::Locale::ja.3
/usr/share/man/man3/DateTime::Locale::ja_JP.3
/usr/share/man/man3/DateTime::Locale::jbo.3
/usr/share/man/man3/DateTime::Locale::jbo_001.3
/usr/share/man/man3/DateTime::Locale::jgo.3
/usr/share/man/man3/DateTime::Locale::jgo_CM.3
/usr/share/man/man3/DateTime::Locale::jmc.3
/usr/share/man/man3/DateTime::Locale::jmc_TZ.3
/usr/share/man/man3/DateTime::Locale::jv.3
/usr/share/man/man3/DateTime::Locale::jv_ID.3
/usr/share/man/man3/DateTime::Locale::ka.3
/usr/share/man/man3/DateTime::Locale::ka_GE.3
/usr/share/man/man3/DateTime::Locale::kab.3
/usr/share/man/man3/DateTime::Locale::kab_DZ.3
/usr/share/man/man3/DateTime::Locale::kaj.3
/usr/share/man/man3/DateTime::Locale::kaj_NG.3
/usr/share/man/man3/DateTime::Locale::kam.3
/usr/share/man/man3/DateTime::Locale::kam_KE.3
/usr/share/man/man3/DateTime::Locale::kcg.3
/usr/share/man/man3/DateTime::Locale::kcg_NG.3
/usr/share/man/man3/DateTime::Locale::kde.3
/usr/share/man/man3/DateTime::Locale::kde_TZ.3
/usr/share/man/man3/DateTime::Locale::kea.3
/usr/share/man/man3/DateTime::Locale::kea_CV.3
/usr/share/man/man3/DateTime::Locale::ken.3
/usr/share/man/man3/DateTime::Locale::ken_CM.3
/usr/share/man/man3/DateTime::Locale::kgp.3
/usr/share/man/man3/DateTime::Locale::kgp_BR.3
/usr/share/man/man3/DateTime::Locale::khq.3
/usr/share/man/man3/DateTime::Locale::khq_ML.3
/usr/share/man/man3/DateTime::Locale::ki.3
/usr/share/man/man3/DateTime::Locale::ki_KE.3
/usr/share/man/man3/DateTime::Locale::kk.3
/usr/share/man/man3/DateTime::Locale::kk_KZ.3
/usr/share/man/man3/DateTime::Locale::kkj.3
/usr/share/man/man3/DateTime::Locale::kkj_CM.3
/usr/share/man/man3/DateTime::Locale::kl.3
/usr/share/man/man3/DateTime::Locale::kl_GL.3
/usr/share/man/man3/DateTime::Locale::kln.3
/usr/share/man/man3/DateTime::Locale::kln_KE.3
/usr/share/man/man3/DateTime::Locale::km.3
/usr/share/man/man3/DateTime::Locale::km_KH.3
/usr/share/man/man3/DateTime::Locale::kn.3
/usr/share/man/man3/DateTime::Locale::kn_IN.3
/usr/share/man/man3/DateTime::Locale::ko.3
/usr/share/man/man3/DateTime::Locale::ko_KP.3
/usr/share/man/man3/DateTime::Locale::ko_KR.3
/usr/share/man/man3/DateTime::Locale::kok.3
/usr/share/man/man3/DateTime::Locale::kok_IN.3
/usr/share/man/man3/DateTime::Locale::kpe.3
/usr/share/man/man3/DateTime::Locale::kpe_GN.3
/usr/share/man/man3/DateTime::Locale::kpe_LR.3
/usr/share/man/man3/DateTime::Locale::ks.3
/usr/share/man/man3/DateTime::Locale::ks_Arab.3
/usr/share/man/man3/DateTime::Locale::ks_Arab_IN.3
/usr/share/man/man3/DateTime::Locale::ks_Deva.3
/usr/share/man/man3/DateTime::Locale::ks_Deva_IN.3
/usr/share/man/man3/DateTime::Locale::ksb.3
/usr/share/man/man3/DateTime::Locale::ksb_TZ.3
/usr/share/man/man3/DateTime::Locale::ksf.3
/usr/share/man/man3/DateTime::Locale::ksf_CM.3
/usr/share/man/man3/DateTime::Locale::ksh.3
/usr/share/man/man3/DateTime::Locale::ksh_DE.3
/usr/share/man/man3/DateTime::Locale::ku.3
/usr/share/man/man3/DateTime::Locale::ku_TR.3
/usr/share/man/man3/DateTime::Locale::kw.3
/usr/share/man/man3/DateTime::Locale::kw_GB.3
/usr/share/man/man3/DateTime::Locale::ky.3
/usr/share/man/man3/DateTime::Locale::ky_KG.3
/usr/share/man/man3/DateTime::Locale::la.3
/usr/share/man/man3/DateTime::Locale::la_VA.3
/usr/share/man/man3/DateTime::Locale::lag.3
/usr/share/man/man3/DateTime::Locale::lag_TZ.3
/usr/share/man/man3/DateTime::Locale::lb.3
/usr/share/man/man3/DateTime::Locale::lb_LU.3
/usr/share/man/man3/DateTime::Locale::lg.3
/usr/share/man/man3/DateTime::Locale::lg_UG.3
/usr/share/man/man3/DateTime::Locale::lij.3
/usr/share/man/man3/DateTime::Locale::lij_IT.3
/usr/share/man/man3/DateTime::Locale::lkt.3
/usr/share/man/man3/DateTime::Locale::lkt_US.3
/usr/share/man/man3/DateTime::Locale::lmo.3
/usr/share/man/man3/DateTime::Locale::lmo_IT.3
/usr/share/man/man3/DateTime::Locale::ln.3
/usr/share/man/man3/DateTime::Locale::ln_AO.3
/usr/share/man/man3/DateTime::Locale::ln_CD.3
/usr/share/man/man3/DateTime::Locale::ln_CF.3
/usr/share/man/man3/DateTime::Locale::ln_CG.3
/usr/share/man/man3/DateTime::Locale::lo.3
/usr/share/man/man3/DateTime::Locale::lo_LA.3
/usr/share/man/man3/DateTime::Locale::lrc.3
/usr/share/man/man3/DateTime::Locale::lrc_IQ.3
/usr/share/man/man3/DateTime::Locale::lrc_IR.3
/usr/share/man/man3/DateTime::Locale::lt.3
/usr/share/man/man3/DateTime::Locale::lt_LT.3
/usr/share/man/man3/DateTime::Locale::lu.3
/usr/share/man/man3/DateTime::Locale::lu_CD.3
/usr/share/man/man3/DateTime::Locale::luo.3
/usr/share/man/man3/DateTime::Locale::luo_KE.3
/usr/share/man/man3/DateTime::Locale::luy.3
/usr/share/man/man3/DateTime::Locale::luy_KE.3
/usr/share/man/man3/DateTime::Locale::lv.3
/usr/share/man/man3/DateTime::Locale::lv_LV.3
/usr/share/man/man3/DateTime::Locale::mai.3
/usr/share/man/man3/DateTime::Locale::mai_IN.3
/usr/share/man/man3/DateTime::Locale::mas.3
/usr/share/man/man3/DateTime::Locale::mas_KE.3
/usr/share/man/man3/DateTime::Locale::mas_TZ.3
/usr/share/man/man3/DateTime::Locale::mdf.3
/usr/share/man/man3/DateTime::Locale::mdf_RU.3
/usr/share/man/man3/DateTime::Locale::mer.3
/usr/share/man/man3/DateTime::Locale::mer_KE.3
/usr/share/man/man3/DateTime::Locale::mfe.3
/usr/share/man/man3/DateTime::Locale::mfe_MU.3
/usr/share/man/man3/DateTime::Locale::mg.3
/usr/share/man/man3/DateTime::Locale::mg_MG.3
/usr/share/man/man3/DateTime::Locale::mgh.3
/usr/share/man/man3/DateTime::Locale::mgh_MZ.3
/usr/share/man/man3/DateTime::Locale::mgo.3
/usr/share/man/man3/DateTime::Locale::mgo_CM.3
/usr/share/man/man3/DateTime::Locale::mi.3
/usr/share/man/man3/DateTime::Locale::mi_NZ.3
/usr/share/man/man3/DateTime::Locale::mk.3
/usr/share/man/man3/DateTime::Locale::mk_MK.3
/usr/share/man/man3/DateTime::Locale::ml.3
/usr/share/man/man3/DateTime::Locale::ml_IN.3
/usr/share/man/man3/DateTime::Locale::mn.3
/usr/share/man/man3/DateTime::Locale::mn_MN.3
/usr/share/man/man3/DateTime::Locale::mn_Mong.3
/usr/share/man/man3/DateTime::Locale::mn_Mong_CN.3
/usr/share/man/man3/DateTime::Locale::mn_Mong_MN.3
/usr/share/man/man3/DateTime::Locale::mni.3
/usr/share/man/man3/DateTime::Locale::mni_Beng.3
/usr/share/man/man3/DateTime::Locale::mni_Beng_IN.3
/usr/share/man/man3/DateTime::Locale::mni_Mtei.3
/usr/share/man/man3/DateTime::Locale::mni_Mtei_IN.3
/usr/share/man/man3/DateTime::Locale::moh.3
/usr/share/man/man3/DateTime::Locale::moh_CA.3
/usr/share/man/man3/DateTime::Locale::mr.3
/usr/share/man/man3/DateTime::Locale::mr_IN.3
/usr/share/man/man3/DateTime::Locale::ms.3
/usr/share/man/man3/DateTime::Locale::ms_Arab.3
/usr/share/man/man3/DateTime::Locale::ms_Arab_BN.3
/usr/share/man/man3/DateTime::Locale::ms_Arab_MY.3
/usr/share/man/man3/DateTime::Locale::ms_BN.3
/usr/share/man/man3/DateTime::Locale::ms_ID.3
/usr/share/man/man3/DateTime::Locale::ms_MY.3
/usr/share/man/man3/DateTime::Locale::ms_SG.3
/usr/share/man/man3/DateTime::Locale::mt.3
/usr/share/man/man3/DateTime::Locale::mt_MT.3
/usr/share/man/man3/DateTime::Locale::mua.3
/usr/share/man/man3/DateTime::Locale::mua_CM.3
/usr/share/man/man3/DateTime::Locale::mus.3
/usr/share/man/man3/DateTime::Locale::mus_US.3
/usr/share/man/man3/DateTime::Locale::my.3
/usr/share/man/man3/DateTime::Locale::my_MM.3
/usr/share/man/man3/DateTime::Locale::myv.3
/usr/share/man/man3/DateTime::Locale::myv_RU.3
/usr/share/man/man3/DateTime::Locale::mzn.3
/usr/share/man/man3/DateTime::Locale::mzn_IR.3
/usr/share/man/man3/DateTime::Locale::naq.3
/usr/share/man/man3/DateTime::Locale::naq_NA.3
/usr/share/man/man3/DateTime::Locale::nb.3
/usr/share/man/man3/DateTime::Locale::nb_NO.3
/usr/share/man/man3/DateTime::Locale::nb_SJ.3
/usr/share/man/man3/DateTime::Locale::nd.3
/usr/share/man/man3/DateTime::Locale::nd_ZW.3
/usr/share/man/man3/DateTime::Locale::nds.3
/usr/share/man/man3/DateTime::Locale::nds_DE.3
/usr/share/man/man3/DateTime::Locale::nds_NL.3
/usr/share/man/man3/DateTime::Locale::ne.3
/usr/share/man/man3/DateTime::Locale::ne_IN.3
/usr/share/man/man3/DateTime::Locale::ne_NP.3
/usr/share/man/man3/DateTime::Locale::nl.3
/usr/share/man/man3/DateTime::Locale::nl_AW.3
/usr/share/man/man3/DateTime::Locale::nl_BE.3
/usr/share/man/man3/DateTime::Locale::nl_BQ.3
/usr/share/man/man3/DateTime::Locale::nl_CW.3
/usr/share/man/man3/DateTime::Locale::nl_NL.3
/usr/share/man/man3/DateTime::Locale::nl_SR.3
/usr/share/man/man3/DateTime::Locale::nl_SX.3
/usr/share/man/man3/DateTime::Locale::nmg.3
/usr/share/man/man3/DateTime::Locale::nmg_CM.3
/usr/share/man/man3/DateTime::Locale::nn.3
/usr/share/man/man3/DateTime::Locale::nn_NO.3
/usr/share/man/man3/DateTime::Locale::nnh.3
/usr/share/man/man3/DateTime::Locale::nnh_CM.3
/usr/share/man/man3/DateTime::Locale::no.3
/usr/share/man/man3/DateTime::Locale::nqo.3
/usr/share/man/man3/DateTime::Locale::nqo_GN.3
/usr/share/man/man3/DateTime::Locale::nr.3
/usr/share/man/man3/DateTime::Locale::nr_ZA.3
/usr/share/man/man3/DateTime::Locale::nso.3
/usr/share/man/man3/DateTime::Locale::nso_ZA.3
/usr/share/man/man3/DateTime::Locale::nus.3
/usr/share/man/man3/DateTime::Locale::nus_SS.3
/usr/share/man/man3/DateTime::Locale::nv.3
/usr/share/man/man3/DateTime::Locale::nv_US.3
/usr/share/man/man3/DateTime::Locale::ny.3
/usr/share/man/man3/DateTime::Locale::ny_MW.3
/usr/share/man/man3/DateTime::Locale::nyn.3
/usr/share/man/man3/DateTime::Locale::nyn_UG.3
/usr/share/man/man3/DateTime::Locale::oc.3
/usr/share/man/man3/DateTime::Locale::oc_ES.3
/usr/share/man/man3/DateTime::Locale::oc_FR.3
/usr/share/man/man3/DateTime::Locale::om.3
/usr/share/man/man3/DateTime::Locale::om_ET.3
/usr/share/man/man3/DateTime::Locale::om_KE.3
/usr/share/man/man3/DateTime::Locale::or.3
/usr/share/man/man3/DateTime::Locale::or_IN.3
/usr/share/man/man3/DateTime::Locale::os.3
/usr/share/man/man3/DateTime::Locale::os_GE.3
/usr/share/man/man3/DateTime::Locale::os_RU.3
/usr/share/man/man3/DateTime::Locale::osa.3
/usr/share/man/man3/DateTime::Locale::osa_US.3
/usr/share/man/man3/DateTime::Locale::pa.3
/usr/share/man/man3/DateTime::Locale::pa_Arab.3
/usr/share/man/man3/DateTime::Locale::pa_Arab_PK.3
/usr/share/man/man3/DateTime::Locale::pa_Guru.3
/usr/share/man/man3/DateTime::Locale::pa_Guru_IN.3
/usr/share/man/man3/DateTime::Locale::pap.3
/usr/share/man/man3/DateTime::Locale::pap_AW.3
/usr/share/man/man3/DateTime::Locale::pap_CW.3
/usr/share/man/man3/DateTime::Locale::pcm.3
/usr/share/man/man3/DateTime::Locale::pcm_NG.3
/usr/share/man/man3/DateTime::Locale::pis.3
/usr/share/man/man3/DateTime::Locale::pis_SB.3
/usr/share/man/man3/DateTime::Locale::pl.3
/usr/share/man/man3/DateTime::Locale::pl_PL.3
/usr/share/man/man3/DateTime::Locale::prg.3
/usr/share/man/man3/DateTime::Locale::prg_001.3
/usr/share/man/man3/DateTime::Locale::ps.3
/usr/share/man/man3/DateTime::Locale::ps_AF.3
/usr/share/man/man3/DateTime::Locale::ps_PK.3
/usr/share/man/man3/DateTime::Locale::pt.3
/usr/share/man/man3/DateTime::Locale::pt_AO.3
/usr/share/man/man3/DateTime::Locale::pt_BR.3
/usr/share/man/man3/DateTime::Locale::pt_CH.3
/usr/share/man/man3/DateTime::Locale::pt_CV.3
/usr/share/man/man3/DateTime::Locale::pt_GQ.3
/usr/share/man/man3/DateTime::Locale::pt_GW.3
/usr/share/man/man3/DateTime::Locale::pt_LU.3
/usr/share/man/man3/DateTime::Locale::pt_MO.3
/usr/share/man/man3/DateTime::Locale::pt_MZ.3
/usr/share/man/man3/DateTime::Locale::pt_PT.3
/usr/share/man/man3/DateTime::Locale::pt_ST.3
/usr/share/man/man3/DateTime::Locale::pt_TL.3
/usr/share/man/man3/DateTime::Locale::qu.3
/usr/share/man/man3/DateTime::Locale::qu_BO.3
/usr/share/man/man3/DateTime::Locale::qu_EC.3
/usr/share/man/man3/DateTime::Locale::qu_PE.3
/usr/share/man/man3/DateTime::Locale::quc.3
/usr/share/man/man3/DateTime::Locale::quc_GT.3
/usr/share/man/man3/DateTime::Locale::raj.3
/usr/share/man/man3/DateTime::Locale::raj_IN.3
/usr/share/man/man3/DateTime::Locale::rhg.3
/usr/share/man/man3/DateTime::Locale::rhg_Rohg.3
/usr/share/man/man3/DateTime::Locale::rhg_Rohg_BD.3
/usr/share/man/man3/DateTime::Locale::rhg_Rohg_MM.3
/usr/share/man/man3/DateTime::Locale::rif.3
/usr/share/man/man3/DateTime::Locale::rif_MA.3
/usr/share/man/man3/DateTime::Locale::rm.3
/usr/share/man/man3/DateTime::Locale::rm_CH.3
/usr/share/man/man3/DateTime::Locale::rn.3
/usr/share/man/man3/DateTime::Locale::rn_BI.3
/usr/share/man/man3/DateTime::Locale::ro.3
/usr/share/man/man3/DateTime::Locale::ro_MD.3
/usr/share/man/man3/DateTime::Locale::ro_RO.3
/usr/share/man/man3/DateTime::Locale::rof.3
/usr/share/man/man3/DateTime::Locale::rof_TZ.3
/usr/share/man/man3/DateTime::Locale::ru.3
/usr/share/man/man3/DateTime::Locale::ru_BY.3
/usr/share/man/man3/DateTime::Locale::ru_KG.3
/usr/share/man/man3/DateTime::Locale::ru_KZ.3
/usr/share/man/man3/DateTime::Locale::ru_MD.3
/usr/share/man/man3/DateTime::Locale::ru_RU.3
/usr/share/man/man3/DateTime::Locale::ru_UA.3
/usr/share/man/man3/DateTime::Locale::rw.3
/usr/share/man/man3/DateTime::Locale::rw_RW.3
/usr/share/man/man3/DateTime::Locale::rwk.3
/usr/share/man/man3/DateTime::Locale::rwk_TZ.3
/usr/share/man/man3/DateTime::Locale::sa.3
/usr/share/man/man3/DateTime::Locale::sa_IN.3
/usr/share/man/man3/DateTime::Locale::sah.3
/usr/share/man/man3/DateTime::Locale::sah_RU.3
/usr/share/man/man3/DateTime::Locale::saq.3
/usr/share/man/man3/DateTime::Locale::saq_KE.3
/usr/share/man/man3/DateTime::Locale::sat.3
/usr/share/man/man3/DateTime::Locale::sat_Deva.3
/usr/share/man/man3/DateTime::Locale::sat_Deva_IN.3
/usr/share/man/man3/DateTime::Locale::sat_Olck.3
/usr/share/man/man3/DateTime::Locale::sat_Olck_IN.3
/usr/share/man/man3/DateTime::Locale::sbp.3
/usr/share/man/man3/DateTime::Locale::sbp_TZ.3
/usr/share/man/man3/DateTime::Locale::sc.3
/usr/share/man/man3/DateTime::Locale::sc_IT.3
/usr/share/man/man3/DateTime::Locale::scn.3
/usr/share/man/man3/DateTime::Locale::scn_IT.3
/usr/share/man/man3/DateTime::Locale::sd.3
/usr/share/man/man3/DateTime::Locale::sd_Arab.3
/usr/share/man/man3/DateTime::Locale::sd_Arab_PK.3
/usr/share/man/man3/DateTime::Locale::sd_Deva.3
/usr/share/man/man3/DateTime::Locale::sd_Deva_IN.3
/usr/share/man/man3/DateTime::Locale::sdh.3
/usr/share/man/man3/DateTime::Locale::sdh_IQ.3
/usr/share/man/man3/DateTime::Locale::sdh_IR.3
/usr/share/man/man3/DateTime::Locale::se.3
/usr/share/man/man3/DateTime::Locale::se_FI.3
/usr/share/man/man3/DateTime::Locale::se_NO.3
/usr/share/man/man3/DateTime::Locale::se_SE.3
/usr/share/man/man3/DateTime::Locale::seh.3
/usr/share/man/man3/DateTime::Locale::seh_MZ.3
/usr/share/man/man3/DateTime::Locale::ses.3
/usr/share/man/man3/DateTime::Locale::ses_ML.3
/usr/share/man/man3/DateTime::Locale::sg.3
/usr/share/man/man3/DateTime::Locale::sg_CF.3
/usr/share/man/man3/DateTime::Locale::shi.3
/usr/share/man/man3/DateTime::Locale::shi_Latn.3
/usr/share/man/man3/DateTime::Locale::shi_Latn_MA.3
/usr/share/man/man3/DateTime::Locale::shi_Tfng.3
/usr/share/man/man3/DateTime::Locale::shi_Tfng_MA.3
/usr/share/man/man3/DateTime::Locale::shn.3
/usr/share/man/man3/DateTime::Locale::shn_MM.3
/usr/share/man/man3/DateTime::Locale::shn_TH.3
/usr/share/man/man3/DateTime::Locale::si.3
/usr/share/man/man3/DateTime::Locale::si_LK.3
/usr/share/man/man3/DateTime::Locale::sid.3
/usr/share/man/man3/DateTime::Locale::sid_ET.3
/usr/share/man/man3/DateTime::Locale::sk.3
/usr/share/man/man3/DateTime::Locale::sk_SK.3
/usr/share/man/man3/DateTime::Locale::sl.3
/usr/share/man/man3/DateTime::Locale::sl_SI.3
/usr/share/man/man3/DateTime::Locale::sma.3
/usr/share/man/man3/DateTime::Locale::sma_NO.3
/usr/share/man/man3/DateTime::Locale::sma_SE.3
/usr/share/man/man3/DateTime::Locale::smj.3
/usr/share/man/man3/DateTime::Locale::smj_NO.3
/usr/share/man/man3/DateTime::Locale::smj_SE.3
/usr/share/man/man3/DateTime::Locale::smn.3
/usr/share/man/man3/DateTime::Locale::smn_FI.3
/usr/share/man/man3/DateTime::Locale::sms.3
/usr/share/man/man3/DateTime::Locale::sms_FI.3
/usr/share/man/man3/DateTime::Locale::sn.3
/usr/share/man/man3/DateTime::Locale::sn_ZW.3
/usr/share/man/man3/DateTime::Locale::so.3
/usr/share/man/man3/DateTime::Locale::so_DJ.3
/usr/share/man/man3/DateTime::Locale::so_ET.3
/usr/share/man/man3/DateTime::Locale::so_KE.3
/usr/share/man/man3/DateTime::Locale::so_SO.3
/usr/share/man/man3/DateTime::Locale::sq.3
/usr/share/man/man3/DateTime::Locale::sq_AL.3
/usr/share/man/man3/DateTime::Locale::sq_MK.3
/usr/share/man/man3/DateTime::Locale::sq_XK.3
/usr/share/man/man3/DateTime::Locale::sr.3
/usr/share/man/man3/DateTime::Locale::sr_Cyrl.3
/usr/share/man/man3/DateTime::Locale::sr_Cyrl_BA.3
/usr/share/man/man3/DateTime::Locale::sr_Cyrl_ME.3
/usr/share/man/man3/DateTime::Locale::sr_Cyrl_RS.3
/usr/share/man/man3/DateTime::Locale::sr_Cyrl_XK.3
/usr/share/man/man3/DateTime::Locale::sr_Latn.3
/usr/share/man/man3/DateTime::Locale::sr_Latn_BA.3
/usr/share/man/man3/DateTime::Locale::sr_Latn_ME.3
/usr/share/man/man3/DateTime::Locale::sr_Latn_RS.3
/usr/share/man/man3/DateTime::Locale::sr_Latn_XK.3
/usr/share/man/man3/DateTime::Locale::ss.3
/usr/share/man/man3/DateTime::Locale::ss_SZ.3
/usr/share/man/man3/DateTime::Locale::ss_ZA.3
/usr/share/man/man3/DateTime::Locale::ssy.3
/usr/share/man/man3/DateTime::Locale::ssy_ER.3
/usr/share/man/man3/DateTime::Locale::st.3
/usr/share/man/man3/DateTime::Locale::st_LS.3
/usr/share/man/man3/DateTime::Locale::st_ZA.3
/usr/share/man/man3/DateTime::Locale::su.3
/usr/share/man/man3/DateTime::Locale::su_Latn.3
/usr/share/man/man3/DateTime::Locale::su_Latn_ID.3
/usr/share/man/man3/DateTime::Locale::sv.3
/usr/share/man/man3/DateTime::Locale::sv_AX.3
/usr/share/man/man3/DateTime::Locale::sv_FI.3
/usr/share/man/man3/DateTime::Locale::sv_SE.3
/usr/share/man/man3/DateTime::Locale::sw.3
/usr/share/man/man3/DateTime::Locale::sw_CD.3
/usr/share/man/man3/DateTime::Locale::sw_KE.3
/usr/share/man/man3/DateTime::Locale::sw_TZ.3
/usr/share/man/man3/DateTime::Locale::sw_UG.3
/usr/share/man/man3/DateTime::Locale::syr.3
/usr/share/man/man3/DateTime::Locale::syr_IQ.3
/usr/share/man/man3/DateTime::Locale::syr_SY.3
/usr/share/man/man3/DateTime::Locale::szl.3
/usr/share/man/man3/DateTime::Locale::szl_PL.3
/usr/share/man/man3/DateTime::Locale::ta.3
/usr/share/man/man3/DateTime::Locale::ta_IN.3
/usr/share/man/man3/DateTime::Locale::ta_LK.3
/usr/share/man/man3/DateTime::Locale::ta_MY.3
/usr/share/man/man3/DateTime::Locale::ta_SG.3
/usr/share/man/man3/DateTime::Locale::te.3
/usr/share/man/man3/DateTime::Locale::te_IN.3
/usr/share/man/man3/DateTime::Locale::teo.3
/usr/share/man/man3/DateTime::Locale::teo_KE.3
/usr/share/man/man3/DateTime::Locale::teo_UG.3
/usr/share/man/man3/DateTime::Locale::tg.3
/usr/share/man/man3/DateTime::Locale::tg_TJ.3
/usr/share/man/man3/DateTime::Locale::th.3
/usr/share/man/man3/DateTime::Locale::th_TH.3
/usr/share/man/man3/DateTime::Locale::ti.3
/usr/share/man/man3/DateTime::Locale::ti_ER.3
/usr/share/man/man3/DateTime::Locale::ti_ET.3
/usr/share/man/man3/DateTime::Locale::tig.3
/usr/share/man/man3/DateTime::Locale::tig_ER.3
/usr/share/man/man3/DateTime::Locale::tk.3
/usr/share/man/man3/DateTime::Locale::tk_TM.3
/usr/share/man/man3/DateTime::Locale::tn.3
/usr/share/man/man3/DateTime::Locale::tn_BW.3
/usr/share/man/man3/DateTime::Locale::tn_ZA.3
/usr/share/man/man3/DateTime::Locale::to.3
/usr/share/man/man3/DateTime::Locale::to_TO.3
/usr/share/man/man3/DateTime::Locale::tok.3
/usr/share/man/man3/DateTime::Locale::tok_001.3
/usr/share/man/man3/DateTime::Locale::tpi.3
/usr/share/man/man3/DateTime::Locale::tpi_PG.3
/usr/share/man/man3/DateTime::Locale::tr.3
/usr/share/man/man3/DateTime::Locale::tr_CY.3
/usr/share/man/man3/DateTime::Locale::tr_TR.3
/usr/share/man/man3/DateTime::Locale::trv.3
/usr/share/man/man3/DateTime::Locale::trv_TW.3
/usr/share/man/man3/DateTime::Locale::trw.3
/usr/share/man/man3/DateTime::Locale::trw_PK.3
/usr/share/man/man3/DateTime::Locale::ts.3
/usr/share/man/man3/DateTime::Locale::ts_ZA.3
/usr/share/man/man3/DateTime::Locale::tt.3
/usr/share/man/man3/DateTime::Locale::tt_RU.3
/usr/share/man/man3/DateTime::Locale::twq.3
/usr/share/man/man3/DateTime::Locale::twq_NE.3
/usr/share/man/man3/DateTime::Locale::tzm.3
/usr/share/man/man3/DateTime::Locale::tzm_MA.3
/usr/share/man/man3/DateTime::Locale::ug.3
/usr/share/man/man3/DateTime::Locale::ug_CN.3
/usr/share/man/man3/DateTime::Locale::uk.3
/usr/share/man/man3/DateTime::Locale::uk_UA.3
/usr/share/man/man3/DateTime::Locale::und.3
/usr/share/man/man3/DateTime::Locale::ur.3
/usr/share/man/man3/DateTime::Locale::ur_IN.3
/usr/share/man/man3/DateTime::Locale::ur_PK.3
/usr/share/man/man3/DateTime::Locale::uz.3
/usr/share/man/man3/DateTime::Locale::uz_Arab.3
/usr/share/man/man3/DateTime::Locale::uz_Arab_AF.3
/usr/share/man/man3/DateTime::Locale::uz_Cyrl.3
/usr/share/man/man3/DateTime::Locale::uz_Cyrl_UZ.3
/usr/share/man/man3/DateTime::Locale::uz_Latn.3
/usr/share/man/man3/DateTime::Locale::uz_Latn_UZ.3
/usr/share/man/man3/DateTime::Locale::vai.3
/usr/share/man/man3/DateTime::Locale::vai_Latn.3
/usr/share/man/man3/DateTime::Locale::vai_Latn_LR.3
/usr/share/man/man3/DateTime::Locale::vai_Vaii.3
/usr/share/man/man3/DateTime::Locale::vai_Vaii_LR.3
/usr/share/man/man3/DateTime::Locale::ve.3
/usr/share/man/man3/DateTime::Locale::ve_ZA.3
/usr/share/man/man3/DateTime::Locale::vec.3
/usr/share/man/man3/DateTime::Locale::vec_IT.3
/usr/share/man/man3/DateTime::Locale::vi.3
/usr/share/man/man3/DateTime::Locale::vi_VN.3
/usr/share/man/man3/DateTime::Locale::vo.3
/usr/share/man/man3/DateTime::Locale::vo_001.3
/usr/share/man/man3/DateTime::Locale::vun.3
/usr/share/man/man3/DateTime::Locale::vun_TZ.3
/usr/share/man/man3/DateTime::Locale::wa.3
/usr/share/man/man3/DateTime::Locale::wa_BE.3
/usr/share/man/man3/DateTime::Locale::wae.3
/usr/share/man/man3/DateTime::Locale::wae_CH.3
/usr/share/man/man3/DateTime::Locale::wal.3
/usr/share/man/man3/DateTime::Locale::wal_ET.3
/usr/share/man/man3/DateTime::Locale::wbp.3
/usr/share/man/man3/DateTime::Locale::wbp_AU.3
/usr/share/man/man3/DateTime::Locale::wo.3
/usr/share/man/man3/DateTime::Locale::wo_SN.3
/usr/share/man/man3/DateTime::Locale::xh.3
/usr/share/man/man3/DateTime::Locale::xh_ZA.3
/usr/share/man/man3/DateTime::Locale::xog.3
/usr/share/man/man3/DateTime::Locale::xog_UG.3
/usr/share/man/man3/DateTime::Locale::yav.3
/usr/share/man/man3/DateTime::Locale::yav_CM.3
/usr/share/man/man3/DateTime::Locale::yi.3
/usr/share/man/man3/DateTime::Locale::yi_001.3
/usr/share/man/man3/DateTime::Locale::yo.3
/usr/share/man/man3/DateTime::Locale::yo_BJ.3
/usr/share/man/man3/DateTime::Locale::yo_NG.3
/usr/share/man/man3/DateTime::Locale::yrl.3
/usr/share/man/man3/DateTime::Locale::yrl_BR.3
/usr/share/man/man3/DateTime::Locale::yrl_CO.3
/usr/share/man/man3/DateTime::Locale::yrl_VE.3
/usr/share/man/man3/DateTime::Locale::yue.3
/usr/share/man/man3/DateTime::Locale::yue_Hans.3
/usr/share/man/man3/DateTime::Locale::yue_Hans_CN.3
/usr/share/man/man3/DateTime::Locale::yue_Hant.3
/usr/share/man/man3/DateTime::Locale::yue_Hant_HK.3
/usr/share/man/man3/DateTime::Locale::zgh.3
/usr/share/man/man3/DateTime::Locale::zgh_MA.3
/usr/share/man/man3/DateTime::Locale::zh.3
/usr/share/man/man3/DateTime::Locale::zh_Hans.3
/usr/share/man/man3/DateTime::Locale::zh_Hans_CN.3
/usr/share/man/man3/DateTime::Locale::zh_Hans_HK.3
/usr/share/man/man3/DateTime::Locale::zh_Hans_MO.3
/usr/share/man/man3/DateTime::Locale::zh_Hans_SG.3
/usr/share/man/man3/DateTime::Locale::zh_Hant.3
/usr/share/man/man3/DateTime::Locale::zh_Hant_HK.3
/usr/share/man/man3/DateTime::Locale::zh_Hant_MO.3
/usr/share/man/man3/DateTime::Locale::zh_Hant_TW.3
/usr/share/man/man3/DateTime::Locale::zu.3
/usr/share/man/man3/DateTime::Locale::zu_ZA.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-DateTime-Locale/7a3ae67849cbe4c41d51b6587fba9867878d99ed
/usr/share/package-licenses/perl-DateTime-Locale/96f969d89e371129342f90e4c815e4abdb7461c4

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
