#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-DateTime-Locale
Version  : 0.46
Release  : 1
URL      : http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/DateTime-Locale-0.46.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/DateTime-Locale-0.46.tar.gz
Summary  : 'Localization support for DateTime.pm'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-1.0 ICU
Requires: perl-DateTime-Locale-doc
BuildRequires : perl(Dist::CheckConflicts)
BuildRequires : perl(Exporter::Tiny)
BuildRequires : perl(List::MoreUtils)
BuildRequires : perl(Module::Implementation)
BuildRequires : perl(Module::Runtime)
BuildRequires : perl(Params::Validate)
BuildRequires : perl(Try::Tiny)

%description
OVERVIEW
The DateTime::Locale modules provide localization data for the
DateTime.pm class.

%package doc
Summary: doc components for the perl-DateTime-Locale package.
Group: Documentation

%description doc
doc components for the perl-DateTime-Locale package.


%prep
%setup -q -n DateTime-Locale-0.46

%build
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/Base.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/Catalog.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/Conflicts.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/aa.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/aa_DJ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/aa_ER.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/aa_ER_SAAHO.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/aa_ET.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/af.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/af_NA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/af_ZA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ak.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ak_GH.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/am.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/am_ET.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_AE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_BH.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_DZ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_EG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_IQ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_JO.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_KW.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_LB.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_LY.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_MA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_OM.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_QA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_SA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_SD.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_SY.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_TN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ar_YE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/as.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/as_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/az.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/az_AZ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/az_Cyrl.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/az_Cyrl_AZ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/az_Latn.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/az_Latn_AZ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/be.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/be_BY.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/bg.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/bg_BG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/bn.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/bn_BD.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/bn_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/bo.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/bo_CN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/bo_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/bs.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/bs_BA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/byn.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/byn_ER.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ca.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ca_ES.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/cch.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/cch_NG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/cop.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/cs.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/cs_CZ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/cy.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/cy_GB.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/da.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/da_DK.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/de.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/de_AT.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/de_BE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/de_CH.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/de_DE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/de_LI.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/de_LU.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/dv.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/dv_MV.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/dz.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/dz_BT.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ee.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ee_GH.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ee_TG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/el.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/el_CY.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/el_GR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/el_POLYTON.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_AS.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_AU.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_BE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_BW.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_BZ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_CA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_Dsrt.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_Dsrt_US.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_GB.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_GU.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_HK.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_IE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_JM.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_MH.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_MP.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_MT.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_NA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_NZ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_PH.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_PK.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_SG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_Shaw.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_TT.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_UM.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_US.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_US_POSIX.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_VI.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_ZA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/en_ZW.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/eo.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_AR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_BO.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_CL.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_CO.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_CR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_DO.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_EC.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_ES.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_GT.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_HN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_MX.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_NI.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_PA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_PE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_PR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_PY.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_SV.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_US.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_UY.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/es_VE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/et.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/et_EE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/eu.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/eu_ES.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fa.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fa_AF.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fa_IR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fi.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fi_FI.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fil.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fil_PH.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fo.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fo_FO.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fr.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fr_BE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fr_CA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fr_CH.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fr_FR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fr_LU.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fr_MC.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fr_SN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fur.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/fur_IT.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ga.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ga_IE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/gaa.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/gaa_GH.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/gez.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/gez_ER.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/gez_ET.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/gl.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/gl_ES.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/gsw.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/gsw_CH.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/gu.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/gu_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/gv.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/gv_GB.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ha.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ha_Arab.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ha_Arab_NG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ha_Arab_SD.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ha_GH.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ha_Latn.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ha_Latn_GH.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ha_Latn_NE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ha_Latn_NG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ha_NE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ha_NG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ha_SD.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/haw.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/haw_US.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/he.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/he_IL.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/hi.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/hi_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/hr.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/hr_HR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/hu.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/hu_HU.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/hy.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/hy_AM.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/hy_AM_REVISED.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ia.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/id.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/id_ID.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ig.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ig_NG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ii.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ii_CN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/is.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/is_IS.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/it.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/it_CH.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/it_IT.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/iu.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ja.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ja_JP.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ka.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ka_GE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kaj.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kaj_NG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kam.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kam_KE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kcg.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kcg_NG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kfo.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kfo_CI.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kk.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kk_Cyrl.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kk_Cyrl_KZ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kk_KZ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kl.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kl_GL.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/km.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/km_KH.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kn.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kn_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ko.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ko_KR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kok.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kok_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kpe.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kpe_GN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kpe_LR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ku.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ku_Arab.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ku_Arab_IQ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ku_Arab_IR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ku_Arab_SY.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ku_IQ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ku_IR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ku_Latn.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ku_Latn_TR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ku_SY.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ku_TR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kw.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/kw_GB.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ky.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ky_KG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ln.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ln_CD.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ln_CG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/lo.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/lo_LA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/lt.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/lt_LT.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/lv.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/lv_LV.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/mk.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/mk_MK.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ml.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ml_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/mn.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/mn_CN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/mn_Cyrl.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/mn_Cyrl_MN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/mn_MN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/mn_Mong.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/mn_Mong_CN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/mo.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/mr.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/mr_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ms.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ms_BN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ms_MY.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/mt.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/mt_MT.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/my.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/my_MM.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/nb.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/nb_NO.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/nds.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/nds_DE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ne.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ne_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ne_NP.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/nl.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/nl_BE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/nl_NL.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/nn.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/nn_NO.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/no.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/nr.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/nr_ZA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/nso.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/nso_ZA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ny.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ny_MW.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/oc.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/oc_FR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/om.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/om_ET.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/om_KE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/or.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/or_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/pa.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/pa_Arab.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/pa_Arab_PK.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/pa_Guru.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/pa_Guru_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/pa_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/pa_PK.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/pl.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/pl_PL.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ps.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ps_AF.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/pt.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/pt_BR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/pt_PT.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ro.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ro_MD.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ro_RO.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/root.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ru.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ru_RU.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ru_UA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/rw.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/rw_RW.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sa.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sa_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/se.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/se_FI.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/se_NO.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sh.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sh_BA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sh_CS.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sh_YU.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/si.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/si_LK.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sid.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sid_ET.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sk.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sk_SK.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sl.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sl_SI.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/so.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/so_DJ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/so_ET.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/so_KE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/so_SO.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sq.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sq_AL.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_BA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_CS.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_Cyrl.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_Cyrl_BA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_Cyrl_CS.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_Cyrl_ME.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_Cyrl_RS.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_Cyrl_YU.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_Latn.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_Latn_BA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_Latn_CS.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_Latn_ME.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_Latn_RS.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_Latn_YU.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_ME.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_RS.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sr_YU.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ss.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ss_SZ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ss_ZA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/st.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/st_LS.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/st_ZA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sv.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sv_FI.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sv_SE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sw.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sw_KE.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/sw_TZ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/syr.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/syr_SY.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ta.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ta_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/te.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/te_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/tg.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/tg_Cyrl.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/tg_Cyrl_TJ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/tg_TJ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/th.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/th_TH.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ti.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ti_ER.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ti_ET.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/tig.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/tig_ER.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/tl.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/tn.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/tn_ZA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/to.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/to_TO.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/tr.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/tr_TR.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/trv.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/trv_TW.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ts.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ts_ZA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/tt.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/tt_RU.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ug.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ug_Arab.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ug_Arab_CN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ug_CN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/uk.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/uk_UA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ur.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ur_IN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ur_PK.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/uz.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/uz_AF.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/uz_Arab.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/uz_Arab_AF.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/uz_Cyrl.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/uz_Cyrl_UZ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/uz_Latn.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/uz_Latn_UZ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/uz_UZ.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ve.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/ve_ZA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/vi.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/vi_VN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/wal.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/wal_ET.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/wo.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/wo_Latn.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/wo_Latn_SN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/wo_SN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/xh.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/xh_ZA.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/yo.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/yo_NG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zh.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zh_CN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zh_HK.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zh_Hans.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zh_Hans_CN.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zh_Hans_HK.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zh_Hans_MO.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zh_Hans_SG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zh_Hant.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zh_Hant_HK.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zh_Hant_MO.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zh_Hant_TW.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zh_MO.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zh_SG.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zh_TW.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zu.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/zu_ZA.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
