#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-DateTime-Locale
Version  : 0.90
Release  : 2
URL      : http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/DateTime-Locale-0.90.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/DateTime-Locale-0.90.tar.gz
Summary  : 'Localization support for DateTime.pm'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-1.0 ICU
Requires: perl-DateTime-Locale-doc
BuildRequires : perl(Devel::Confess)
BuildRequires : perl(Dist::CheckConflicts)
BuildRequires : perl(Exporter::Tiny)
BuildRequires : perl(List::MoreUtils)
BuildRequires : perl(Module::Implementation)
BuildRequires : perl(Module::Runtime)
BuildRequires : perl(Params::Validate)
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Test::Requires)
BuildRequires : perl(Test::Warnings)
BuildRequires : perl(Try::Tiny)

%description
OVERVIEW
The DateTime::Locale modules provide localization data for the
DateTime.pm class.

%package doc
Summary: doc components for the perl-DateTime-Locale package.
Group: Documentation

%description doc
doc components for the perl-DateTime-Locale package.


%prep
%setup -q -n DateTime-Locale-0.90

%build
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/Base.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/Catalog.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/Conflicts.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/Data.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/FromData.pm
/usr/lib/perl5/site_perl/5.22.0/DateTime/Locale/Util.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
